### ISSUE TITLE
Get a list of items from Parse

### ISSUE THREAD

**Issue by eusthace811** [aaronksaunders/parse-starter-ionic#1]
Hi Aaron,

I follow all your work and i have to say you always really great.
Thank you for all help you give to us.

This time, i just would like to ask you, is it possible to you publish an example of get a list of items from Parse and fetch data from the User (pointer to a User) class too at the same time?

Thanks in advance,

jl

**Comment by aaronksaunders** [comment]
@jlsuarezs  here is a sample

``` Javascript
var TutorSession = Parse.Object.extend("TutorSession");
var query = new Parse.Query(TutorSession);
// get all related objects
query.include(["user","place","tutor"]);
query.find({
    success: function(_response) {
        //console.log("myTutorSession.query: " + JSON.stringify(_response,null,2));
        for (var i = 0; i < _response.length; i++) {
          var session = _response[i];
          console.log("user name: " + session.get("user").get("first_name"));
          console.log("location name: " + session.get("place").get("Location"));    
          console.log("tutor name: " + session.get("tutor").get("first_name"));      
        }
    }
});
```

based off of the Parse objects created here:

Screenshot of Users Objects
![Appcelerator Alloy](https://raw.githubusercontent.com/aaronksaunders/parse-starter-appC/master/images/parse_users.png)

Screenshot of Places Objects
![Appcelerator Alloy](https://raw.githubusercontent.com/aaronksaunders/parse-starter-appC/master/images/parse_places.png)

Screenshot of Tutor Sessions Objects
![Appcelerator Alloy](https://raw.githubusercontent.com/aaronksaunders/parse-starter-appC/master/images/parse_tutor_sessions.png)

**Comment by aaronksaunders** [comment]
I will augment the starter example to show this.
