### ISSUE TITLE
doesnt work on real android devices

### ISSUE THREAD

**Issue by lukeyangskywalker** [aaronksaunders/parse-starter-ionic#4]
tested on note 2, note 4

**Comment by aaronksaunders** [comment]
can you be a bit more specific? what version of android are you running on the devices? what issues are you running into... by "Real Android Devices" does that mean it works when you run the code in the browser?

**Comment by nicktcode** [comment]
yes if you deploy and run the app on an android device the app wont load (just show the header which is also not centered and under it a white/blank page). In the browser it seems to work fine..

**Comment by aaronksaunders** [comment]
@nthommen @lukeyangskywalker This is the lack of whitelist specification in the app

See http://docs.ionic.io/docs/cordova-whitelist

I am also  updating the project and the readme to account for this, thx for bringing it to my attention

**Comment by nicktcode** [comment]
so I should add the whitelist plugin and it should work?
Would really appreciate if I can use your project as my starter

**Comment by aaronksaunders** [comment]
@nthommen yes... see comments I added to beginning of readme.md

**Comment by nicktcode** [comment]
great it works! Thanks so much :-) :+1:
